<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BaseOutputPath>..\Artifacts\MonoGame.Imaging</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Containers\Specialized\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonoGame.StbSharp\MonoGame.StbSharp.csproj" />
    <ProjectReference Include="..\MonoGame.Utilities\MonoGame.Utilities.csproj" />
  </ItemGroup>
</Project>
