<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <DefineConstants>OPENGL;OPENAL;XNADESIGNPROVIDED;LINUX;DESKTOPGL;SUPPORTS_EFX;NETSTANDARD;NVORBIS</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <Description>The MonoGame runtime supporting Windows, Linux and macOS using SDL2 and OpenGL.</Description>
    <PackageTags>monogame;.net core;core;.net standard;standard;desktopgl</PackageTags>
    <PackageId>MonoGame.Framework.DesktopGL</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="Graphics\Indices\**" />
    <Compile Remove="obj\**" />
    <Compile Remove="Platform\**\*" />
    <EmbeddedResource Remove="Graphics\Indices\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="bin\**" />
    <None Remove="Graphics\Indices\**" />
    <None Remove="obj\**" />
    <None Remove="Platform\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Graphics\GraphicsAdapter.cs" />
    <Compile Remove="Media\SongCollection.cs" />
    <Compile Remove="Media\SongPart.cs" />
    <Compile Remove="Media\Video.cs" />
    <Compile Remove="Media\VideoPlayer.cs" />
    <Compile Remove="Content\ContentReaders\VideoReader.cs" />
    <Compile Remove="Input\MessageBox.cs" />
    <Compile Remove="Input\KeyboardInput.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Platform\Graphics\OpenGL\OpenGL.SDL.cs" />
    <Compile Include="Platform\Graphics\RenderTargetBindingArrayComparer.cs" />
    <Compile Include="Platform\Graphics\Shader\Shader.Structure.cs" />
    <Compile Include="Platform\Input\Joystick.Instance.SDL.cs" />
    <Compile Include="Platform\Input\Touch\TouchPanelCapabilities.SDL.cs" />
    <Compile Include="Platform\SDL\SDL.Touch.cs" />
    <Compile Include="Platform\SDL\SDL.Display.cs" />
    <Compile Include="Platform\SDL\SDL.Drop.cs" />
    <Compile Include="Platform\SDL\SDL.GameController.cs" />
    <Compile Include="Platform\SDL\SDL.GL.cs" />
    <Compile Include="Platform\SDL\SDL.Haptic.cs" />
    <Compile Include="Platform\SDL\SDL.Joystick.cs" />
    <Compile Include="Platform\SDL\SDL.Keyboard.cs" />
    <Compile Include="Platform\SDL\SDL.Mouse.cs" />
    <Compile Include="Platform\SDL\SDL.Window.cs" />
    <Compile Include="Platform\ThreadHelper.cs" />
    <Compile Include="Platform\TitleContainer.Desktop.cs" />
    <Compile Include="Platform\SDL\SDL2.cs" />
    <Compile Include="Platform\SDL\SDLGamePlatform.cs" />
    <Compile Include="Platform\SDL\SDLGameWindow.cs" />
    <Compile Include="Platform\Utilities\AssemblyHelper.cs" />
    <Compile Include="Platform\Utilities\DummyTaskbarList.cs" />
    <Compile Include="Platform\Utilities\FuncLoader.Desktop.cs" />
    <Compile Include="Platform\Utilities\InteropHelpers.cs" />
    <Compile Include="Platform\Media\Song.NVorbis.cs" />
    <Compile Include="Platform\Input\GamePad.SDL.cs" />
    <Compile Include="Platform\Input\Joystick.SDL.cs" />
    <Compile Include="Platform\Input\Keyboard.SDL.cs" />
    <Compile Include="Platform\Input\KeyboardUtil.SDL.cs" />
    <Compile Include="Platform\Input\KeysHelper.cs" />
    <Compile Include="Platform\Input\Mouse.SDL.cs" />
    <Compile Include="Platform\Input\MouseCursor.SDL.cs" />
    <Compile Include="Platform\Graphics\GraphicsContext.SDL.cs" />
    <Compile Include="Platform\Graphics\GraphicsAdapter.Legacy.cs" />
    <Compile Include="Platform\GamePlatform.Desktop.cs" />
    <Compile Include="Platform\GraphicsDeviceManager.SDL.cs" />
    <Compile Include="Platform\Utilities\TaskbarList.Desktop.cs" />
    <Compile Include="Platform\Windows\WindowsTaskbarList.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="MonoGame.bmp">
      <LogicalName>MonoGame.bmp</LogicalName>
    </EmbeddedResource>
    
    <EmbeddedResource Include="..\ThirdParty\SDL_GameControllerDB\gamecontrollerdb.txt">
      <LogicalName>gamecontrollerdb.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\ThirdParty\Dependencies\openal-soft\Windows\x86\soft_oal.dll">
      <Link>x86\soft_oal.dll</Link>
      <PackagePath>runtimes\win-x86\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\ThirdParty\Dependencies\SDL\Windows\x86\SDL2.dll">
      <Link>x86\SDL2.dll</Link>
      <PackagePath>runtimes\win-x86\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="..\ThirdParty\Dependencies\openal-soft\Windows\x64\soft_oal.dll">
      <Link>x64\soft_oal.dll</Link>
      <PackagePath>runtimes\win-x64\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\ThirdParty\Dependencies\SDL\Windows\x64\SDL2.dll">
      <Link>x64\SDL2.dll</Link>
      <PackagePath>runtimes\win-x64\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="..\ThirdParty\Dependencies\openal-soft\Linux\x64\libopenal.so.1">
      <Link>x64\libopenal.so.1</Link>
      <PackagePath>runtimes\linux-x64\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\ThirdParty\Dependencies\SDL\Linux\x64\libSDL2-2.0.so.0">
      <Link>x64\libSDL2-2.0.so.0</Link>
      <PackagePath>runtimes\linux-x64\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="..\ThirdParty\Dependencies\openal-soft\Linux\x86\libopenal.so.1">
      <Link>x86\libopenal.so.1</Link>
      <PackagePath>runtimes\linux-x86\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="..\ThirdParty\Dependencies\openal-soft\MacOS\Universal\libopenal.1.dylib">
      <Link>libopenal.1.dylib</Link>
      <PackagePath>runtimes\osx\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\ThirdParty\Dependencies\SDL\MacOS\Universal\libSDL2-2.0.0.dylib">
      <Link>libSDL2-2.0.0.dylib</Link>
      <PackagePath>runtimes\osx\native</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="MonoGame.Framework.DesktopGL.targets" PackagePath="build" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonoGame.Imaging\MonoGame.Imaging.csproj" />
    <ProjectReference Include="..\MonoGame.Utilities\MonoGame.Utilities.csproj" />
    <ProjectReference Include="..\ThirdParty\VorbisPizza\NVorbis\NVorbis.csproj" />
  </ItemGroup>

  <Import Project="Platform\OpenGL.targets" />
  <Import Project="Platform\OpenAL.targets" />
</Project>
