<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BaseOutputPath>..\Artifacts\MonoGame.StbSharp</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ThirdParty\StbSharp\Image\src\**\*.cs" Exclude="..\ThirdParty\StbSharp\Image\src\obj\**">
      <Link>ImageRead\%(FileName)%(Extension)</Link>
    </Compile>

    <Compile Include="..\ThirdParty\StbSharp\ImageWrite\src\**\*.cs" Exclude="..\ThirdParty\StbSharp\ImageWrite\src\obj\**">
      <Link>ImageWrite\%(FileName)%(Extension)</Link>
    </Compile>

    <Compile Include="..\ThirdParty\StbSharp\TrueType\src\**\*.cs" Exclude="..\ThirdParty\StbSharp\TrueType\src\obj\**">
      <Link>TrueType\%(FileName)%(Extension)</Link>
    </Compile>
    
    <Compile Include="..\ThirdParty\StbSharp\Shared\src\**\*.cs" Exclude="..\ThirdParty\StbSharp\Shared\src\obj\**">
      <Link>Shared\%(FileName)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="..\ThirdParty\StbSharp\Image\src\ImageRead.Gif.cs" />
    <Compile Remove="..\ThirdParty\StbSharp\Image\src\ImageRead.Psd.cs" />
  </ItemGroup>

</Project>
