<Project>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);DIRECTX</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Platform\Graphics\GraphicsAdapter.DirectX.cs" />
    <Compile Include="Platform\Graphics\Effect\EffectResource.DirectX.cs" />
    <Compile Include="Platform\Graphics\GraphicsCapabilities.DirectX.cs" />
    <Compile Include="Platform\Graphics\GraphicsDebug.DirectX.cs" />
    <Compile Include="Platform\Graphics\GraphicsDevice.DirectX.cs" />
    <Compile Include="Platform\Graphics\OcclusionQuery.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\IRenderTarget.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\RenderTarget2D.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\RenderTarget3D.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\RenderTargetCube.DirectX.cs" />
    <Compile Include="Platform\Graphics\SamplerStateCollection.DirectX.cs" />
    <Compile Include="Platform\Graphics\Shader\ConstantBuffer.DirectX.cs" />
    <Compile Include="Platform\Graphics\Shader\Shader.DirectX.cs" />
    <Compile Include="Platform\Graphics\States\BlendState.DirectX.cs" />
    <Compile Include="Platform\Graphics\States\TargetBlendState.DirectX.cs" />
    <Compile Include="Platform\Graphics\States\DepthStencilState.DirectX.cs" />
    <Compile Include="Platform\Graphics\States\RasterizerState.DirectX.cs" />
    <Compile Include="Platform\Graphics\States\SamplerState.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\Texture.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\Texture2D.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\Texture3D.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\TextureCollection.DirectX.cs" />
    <Compile Include="Platform\Graphics\Textures\TextureCube.DirectX.cs" />
	  <Compile Include="Platform\Graphics\Textures\SwapChainRenderTarget.DirectX.cs" />
    <Compile Include="Platform\Graphics\Primitives\ImmutableVertexInputLayout.cs" />
    <Compile Include="Platform\Graphics\Primitives\IndexBuffer.DirectX.cs" />
    <Compile Include="Platform\Graphics\Primitives\InputLayoutCache.cs" />
    <Compile Include="Platform\Graphics\Primitives\VertexBuffer.DirectX.cs" />
    <Compile Include="Platform\Graphics\Primitives\VertexBufferBindings.DirectX.cs" />
    <Compile Include="Platform\Graphics\Primitives\VertexElement.DirectX.cs" />
    <Compile Include="Platform\Graphics\Primitives\VertexInputLayout.DirectX.cs" />
    <Compile Include="Platform\Graphics\Primitives\IndexElementTypeExtensions.DirectX.cs" />
    <Compile Include="Platform\Windows\SharpDXHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Platform\Graphics\Effect\Resources\AlphaTestEffect.dx11.mgfxo" />
    <EmbeddedResource Include="Platform\Graphics\Effect\Resources\BasicEffect.dx11.mgfxo" />
    <EmbeddedResource Include="Platform\Graphics\Effect\Resources\DualTextureEffect.dx11.mgfxo" />
    <EmbeddedResource Include="Platform\Graphics\Effect\Resources\EnvironmentMapEffect.dx11.mgfxo" />
    <EmbeddedResource Include="Platform\Graphics\Effect\Resources\SkinnedEffect.dx11.mgfxo" />
    <EmbeddedResource Include="Platform\Graphics\Effect\Resources\SpriteEffect.dx11.mgfxo" />
  </ItemGroup>

</Project>
